"""
Author: L. Saetta
Date last modified: 2026-06-22
License: MIT
Description: Command-line runner for exported Agent Factory deployment scripts.
"""

from __future__ import annotations

# pylint: disable=protected-access

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

from agent_factory_api.app import (
    _build_run_outputs,
    _build_steps,
    _commands_by_step_id,
)
from agent_factory_api.commands import build_deployment_plan
from agent_factory_api.executor import (
    CommandExecutionError,
    execute_live_deployment_commands,
)
from agent_factory_api.models import validate_deployment_payload
from agent_factory_api.ready_script import (
    OCIR_PASSWORD_MARKER,
    OPENAI_API_KEY_MARKER,
)
from agent_factory_api.resources import (
    ResourceProvisioningError,
    provision_foundation_resources,
)

SECRET_MARKERS = {
    "openai_api_key": (OPENAI_API_KEY_MARKER, "OPENAI_API_KEY"),
    "ocir_password": (OCIR_PASSWORD_MARKER, "OCIR_PASSWORD"),
}


def main(argv: list[str] | None = None) -> int:
    """Run a live Agent Factory deployment from an exported payload.

    Args:
        argv: Optional command-line arguments.

    Returns:
        int: Process exit code.
    """

    args = _parse_args(argv)
    try:
        raw_payload = _load_payload(args.payload)
        resolved_payload = _resolve_secret_markers(raw_payload)
        validation = validate_deployment_payload(resolved_payload)
        if validation.errors:
            _print_error("Deployment input validation failed.", validation.errors)
            return 2

        assert validation.payload is not None
        payload = dict(validation.payload)
        payload["dry_run"] = False
        outputs = run_ready_deployment(payload)
    except (
        OSError,
        ValueError,
        ResourceProvisioningError,
        CommandExecutionError,
    ) as exc:
        _print_error(str(exc))
        return 1

    print(json.dumps(outputs, indent=2, sort_keys=True))
    return 0


def run_ready_deployment(payload: dict[str, Any]) -> dict[str, Any]:
    """Execute the live deployment workflow used by exported scripts.

    Args:
        payload: Validated live deployment payload.

    Returns:
        dict[str, Any]: Non-secret deployment outputs.

    Raises:
        ResourceProvisioningError: If foundation resource provisioning fails.
        CommandExecutionError: If a Docker, OCIR, or Hosted Application command
            fails.
    """

    resource_result = provision_foundation_resources(
        payload,
        progress_callback=_print_progress,
    )
    plan_payload = dict(payload)
    plan_payload["compartment"] = resource_result.compartment_id
    plan_payload["genai_project"] = resource_result.project.project_id
    plan_payload["object_storage_namespace"] = resource_result.bucket.namespace_name
    plan_payload["vector_store_name"] = resource_result.vector_store.vector_store_id
    if resource_result.connector is not None:
        plan_payload["connector_name"] = resource_result.connector.connector_id

    plan = build_deployment_plan(plan_payload, dry_run=False)
    steps = _build_steps(plan_payload, plan["commands"])
    execution_outputs = execute_live_deployment_commands(
        plan_payload,
        _commands_by_step_id(steps),
        _print_progress,
    )
    return _build_run_outputs(
        plan_payload=plan_payload,
        plan=plan,
        resource_result=resource_result,
        dry_run=False,
        execution_outputs=execution_outputs,
    )


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Parse command-line arguments.

    Args:
        argv: Optional command-line arguments.

    Returns:
        argparse.Namespace: Parsed arguments.
    """

    parser = argparse.ArgumentParser(
        description="Run an exported Agent Factory deployment script payload."
    )
    parser.add_argument(
        "--payload",
        required=True,
        help="Path to the JSON deployment payload generated by the shell script.",
    )
    return parser.parse_args(argv)


def _load_payload(payload_path: str) -> dict[str, Any]:
    """Load a deployment payload from disk.

    Args:
        payload_path: JSON payload file path.

    Returns:
        dict[str, Any]: Loaded payload.

    Raises:
        ValueError: If the payload is not a JSON object.
    """

    with Path(payload_path).open("r", encoding="utf-8") as payload_file:
        payload = json.load(payload_file)
    if not isinstance(payload, dict):
        raise ValueError("Deployment payload must be a JSON object.")
    return payload


def _resolve_secret_markers(payload: dict[str, Any]) -> dict[str, Any]:
    """Replace generated secret markers with runtime environment values.

    Args:
        payload: Payload loaded from the generated script.

    Returns:
        dict[str, Any]: Payload with secrets restored from environment values.

    Raises:
        ValueError: If a required secret environment variable is missing.
    """

    resolved_payload = dict(payload)
    for field_name, (marker, environment_name) in SECRET_MARKERS.items():
        if resolved_payload.get(field_name) != marker:
            continue
        secret_value = os.environ.get(environment_name)
        if not secret_value:
            raise ValueError(f"{environment_name} is required.")
        resolved_payload[field_name] = secret_value
    return resolved_payload


def _print_progress(
    step_id: str, status: str, outputs: dict[str, Any] | None = None
) -> None:
    """Print a human-readable progress line to standard error.

    Args:
        step_id: Workflow step identifier.
        status: Step status.
        outputs: Optional non-secret step outputs.
    """

    suffix = f" {json.dumps(outputs, sort_keys=True)}" if outputs else ""
    print(f"[{step_id}] {status}{suffix}", file=sys.stderr)


def _print_error(message: str, details: dict[str, str] | None = None) -> None:
    """Print an error message to standard error.

    Args:
        message: Error message.
        details: Optional field-level validation details.
    """

    print(f"ERROR: {message}", file=sys.stderr)
    if details:
        print(json.dumps(details, indent=2, sort_keys=True), file=sys.stderr)


if __name__ == "__main__":
    raise SystemExit(main())
